name: radio_stats
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pip
  - pip:
    - -e git+https://github.com/keflavich/gaussfitter.git#egg=gaussfitter
